# Generated by Django 6.0.4 on 2026-04-07 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'especialidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'db_table': 'municipios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('perfil', models.CharField(choices=[('super_admin', 'Super Admin'), ('gestor_municipal', 'Gestor Municipal'), ('gestor_upa', 'Gestor de UPA'), ('medico', 'Médico')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.municipio')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='api.especialidade')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='api.medico')),
            ],
            options={
                'db_table': 'escalas',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_atendimento', 'Em Atendimento'), ('em_pausa', 'Em Pausa'), ('encerrado', 'Encerrado')], default='em_atendimento', max_length=20)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='api.escala')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.medico')),
            ],
            options={
                'db_table': 'turnos',
                'ordering': ['-iniciado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('inicio', 'Início'), ('pausa', 'Pausa'), ('retorno', 'Retorno'), ('encerramento', 'Encerramento')], max_length=20)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.turno')),
            ],
            options={
                'db_table': 'registros_turno',
                'ordering': ['registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='UPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('especialidades', models.ManyToManyField(blank=True, related_name='upas', to='api.especialidade')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upas', to='api.municipio')),
            ],
            options={
                'verbose_name': 'UPA',
                'verbose_name_plural': 'UPAs',
                'db_table': 'upas',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='upa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='api.upa'),
        ),
        migrations.AddField(
            model_name='escala',
            name='upa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='api.upa'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('critico', 'Crítico'), ('aviso', 'Aviso'), ('informativo', 'Informativo')], max_length=20)),
                ('mensagem', models.TextField()),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.municipio')),
                ('upa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.upa')),
            ],
            options={
                'db_table': 'alertas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='upa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.upa'),
        ),
    ]
