# Generated by Django 6.0.4 on 2026-04-12 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_upa_latitude_upa_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRedefinicaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_redefinicao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tokens_redefinicao_senha',
            },
        ),
    ]
