# Generated by Django 6.0.4 on 2026-04-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tokens_redefinicao_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='uf',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='medico',
            unique_together={('crm', 'uf')},
        ),
    ]
